---
- name: Deploy static website
  hosts: servers
  remote_user: root

  tasks:
    - name: Clone git repository
      git:
        repo: "https://github.com/tanwigeetika1618/Slack_clone.git"
        dest: /var/www/Slack_clone
        update: true

    - name: Copy nginx conf file
      ansible.builtin.template:
        src: slack.conf.j2
        dest: /etc/nginx/conf.d/slack.conf

      notify: Reload ngnix

  handlers:
    - name: Reload ngnix
      systemd:
        name: nginx
        state: reloaded
