---
- name: Install nginx on server
  hosts: servers
  remote_user: root
  vars:
    packages:
      - name: nginx
        when: "'nginx' not in ansible_facts.packages"
      - name: git
        when: "'git' not in ansible_facts.packages"

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Check if nginx is installed
      ansible.builtin.debug:
        msg: "nginx is already installed!"
      when: "'nginx' in ansible_facts.packages"

    - name: Check if git is installed
      ansible.builtin.debug:
        msg: "git is already installed!"
      when: "'git' in ansible_facts.packages"

    - name: Install nginx and git packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: present
      loop: "{{ packages }}"
      when: "'item.name' not in ansible_facts.packages"
      notify:
        - Start nginx service
        - Open port 80 in the firewall for nginx
        - Reload firewall

  handlers:
    - name: Start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Open port 80 in the firewall for nginx
      shell: firewall-cmd --zone=public --add-port=80/tcp --permanent

    - name: Reload firewall
      shell: firewall-cmd --reload