---
- name: install nginx on servera
  hosts: servers
  remote_user: root

  tasks: 
    - name: check if nginx is installed
      command: rpm -q nginx
      register: is_nginx_installed
      ignore_errors: yes

    - name: install nginx
      dnf: 
         name: nginx
         state: latest
      when: is_nginx_installed.rc != 0

    - name: start nginx service
      service: 
         name: nginx
         state: started
         enabled: yes
      
    - name: install git
      dnf:
         name: git
         state: present

    - name: open port 80 in the firewall for nginx
      shell: firewall-cmd --zone=public --add-port=80/tcp --permanent
        
    - name: reload firewall
      shell: firewall-cmd --reload
         
